import { z } from 'zod';
export const NotificationSchema = z.object({
  id: z.string(),
  userId: z.string(),
  type: z.string(),
  templateVersion: z.number().int(),
  payload: z.record(z.unknown()),
  channel: z.enum(['email', 'in-app', 'sms']),
  preferenceCategory: z.string(),
  priority: z.enum(['low', 'normal', 'high', 'urgent']),
  status: z.enum([
    'queued',
    'scheduled',
    'rendering',
    'sending',
    'delivered',
    'retrying',
    'failed',
    'suppressed',
    'cancelled',
  ]),
  scheduledAt: z.string().optional(),
  deliveryAttempts: z.number().int().min(0),
  providerReference: z.string().optional(),
  correlationId: z.string(),
  createdAt: z.string(),
  deliveredAt: z.string().optional(),
  failedAt: z.string().optional(),
  failureReason: z.string().optional(),
});
