export { hasCapability } from './permission-policy.js';
export { isAssignedTeacher, getAccessibleStudents } from './teacher-student-access.js';
export { createFeedbackVersion } from './feedback-versioning.js';
export { acquireLock, isLockExpired, canTakeOver } from './review-lock.js';
export { createConfirmation, isConfirmationStale } from './sensitive-action.js';
export { canStartImpersonation, isImpersonationExpired } from './impersonation-policy.js';
export { createAssignment, publishAssignment, archiveAssignment } from './assignment-service.js';
export { createModerationCase, canTransitionModeration } from './moderation-state-machine.js';
export { recordAdminAction } from './user-administration.js';
export { createEntitlementAdjustmentRequest, confirmAdjustmentRequest } from './entitlement-adjustment-policy.js';
export { createScoringSupportAction } from './scoring-support.js';
export { filterAuditEntries } from './audit-query.js';
